
package com.xiakee.wcf.logist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BsiBuyQueryAPI", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://218.244.133.186:11936/BsiBuyQueryAPI?singleWsdl")
public class BsiBuyQueryAPI
    extends Service
{

    private final static URL BSIBUYQUERYAPI_WSDL_LOCATION;
    private final static WebServiceException BSIBUYQUERYAPI_EXCEPTION;
    private final static QName BSIBUYQUERYAPI_QNAME = new QName("http://tempuri.org/", "BsiBuyQueryAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://218.244.133.186:11936/BsiBuyQueryAPI?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSIBUYQUERYAPI_WSDL_LOCATION = url;
        BSIBUYQUERYAPI_EXCEPTION = e;
    }

    public BsiBuyQueryAPI() {
        super(__getWsdlLocation(), BSIBUYQUERYAPI_QNAME);
    }

    public BsiBuyQueryAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSIBUYQUERYAPI_QNAME, features);
    }

    public BsiBuyQueryAPI(URL wsdlLocation) {
        super(wsdlLocation, BSIBUYQUERYAPI_QNAME);
    }

    public BsiBuyQueryAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSIBUYQUERYAPI_QNAME, features);
    }

    public BsiBuyQueryAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BsiBuyQueryAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBsiBuyQueryAPI
     */
    @WebEndpoint(name = "BasicHttpBinding_IBsiBuyQueryAPI")
    public IBsiBuyQueryAPI getBasicHttpBindingIBsiBuyQueryAPI() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBsiBuyQueryAPI"), IBsiBuyQueryAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBsiBuyQueryAPI
     */
    @WebEndpoint(name = "BasicHttpBinding_IBsiBuyQueryAPI")
    public IBsiBuyQueryAPI getBasicHttpBindingIBsiBuyQueryAPI(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBsiBuyQueryAPI"), IBsiBuyQueryAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSIBUYQUERYAPI_EXCEPTION!= null) {
            throw BSIBUYQUERYAPI_EXCEPTION;
        }
        return BSIBUYQUERYAPI_WSDL_LOCATION;
    }

}
