
package com.xiakee.wcf.logist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBsiBuyQueryAPI", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBsiBuyQueryAPI {


    /**
     * 
     * @param boxNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BoxOpen", action = "http://tempuri.org/IBsiBuyQueryAPI/BoxOpen")
    @WebResult(name = "BoxOpenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BoxOpen", targetNamespace = "http://tempuri.org/", className = "com.xiakee.wcf.logist.BoxOpen")
    @ResponseWrapper(localName = "BoxOpenResponse", targetNamespace = "http://tempuri.org/", className = "com.xiakee.wcf.logist.BoxOpenResponse")
    public String boxOpen(
        @WebParam(name = "boxNo", targetNamespace = "http://tempuri.org/")
        String boxNo);

    /**
     * 
     * @param expressno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Open", action = "http://tempuri.org/IBsiBuyQueryAPI/Open")
    @WebResult(name = "OpenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Open", targetNamespace = "http://tempuri.org/", className = "com.xiakee.wcf.logist.Open")
    @ResponseWrapper(localName = "OpenResponse", targetNamespace = "http://tempuri.org/", className = "com.xiakee.wcf.logist.OpenResponse")
    public String open(
        @WebParam(name = "expressno", targetNamespace = "http://tempuri.org/")
        String expressno);

}
