
package com.xiakee.service.wcf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SjzyBatchDataOperate", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://218.244.133.186:11927/SjzyBatchDataOperate?singleWsdl")
public class SjzyBatchDataOperate
    extends Service
{

    private final static URL SJZYBATCHDATAOPERATE_WSDL_LOCATION;
    private final static WebServiceException SJZYBATCHDATAOPERATE_EXCEPTION;
    private final static QName SJZYBATCHDATAOPERATE_QNAME = new QName("http://tempuri.org/", "SjzyBatchDataOperate");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://218.244.133.186:11927/SjzyBatchDataOperate?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SJZYBATCHDATAOPERATE_WSDL_LOCATION = url;
        SJZYBATCHDATAOPERATE_EXCEPTION = e;
    }

    public SjzyBatchDataOperate() {
        super(__getWsdlLocation(), SJZYBATCHDATAOPERATE_QNAME);
    }

    public SjzyBatchDataOperate(WebServiceFeature... features) {
        super(__getWsdlLocation(), SJZYBATCHDATAOPERATE_QNAME, features);
    }

    public SjzyBatchDataOperate(URL wsdlLocation) {
        super(wsdlLocation, SJZYBATCHDATAOPERATE_QNAME);
    }

    public SjzyBatchDataOperate(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SJZYBATCHDATAOPERATE_QNAME, features);
    }

    public SjzyBatchDataOperate(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SjzyBatchDataOperate(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISjzyBatchDataOperate
     */
    @WebEndpoint(name = "BasicHttpBinding_ISjzyBatchDataOperate")
    public ISjzyBatchDataOperate getBasicHttpBindingISjzyBatchDataOperate() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISjzyBatchDataOperate"), ISjzyBatchDataOperate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISjzyBatchDataOperate
     */
    @WebEndpoint(name = "BasicHttpBinding_ISjzyBatchDataOperate")
    public ISjzyBatchDataOperate getBasicHttpBindingISjzyBatchDataOperate(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISjzyBatchDataOperate"), ISjzyBatchDataOperate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SJZYBATCHDATAOPERATE_EXCEPTION!= null) {
            throw SJZYBATCHDATAOPERATE_EXCEPTION;
        }
        return SJZYBATCHDATAOPERATE_WSDL_LOCATION;
    }

}
